
import markovchain
import pandas as pd
import numpy as np
import sys

from benchmark_from_AFICS import benchmark_from_AFICS
from benchmark_given_matrix import benchmark_given_matrix

if __name__ == "__main__":

    #Parameters common to both benchmark methods. These are explained in the documentation of benchmark_source
    size_smallest_subsample=1
    step_of_subsampling=1
    adress_results="./benchmark_results"
    LIST_METHODS=['Gaussian', 'GaussianSlutsky', 'BasicChi2', 'BasicSlutskyChi2', 'FreerChi2', 'FreerSlutskyChi2']


    #This benchmarking can be done in two ways:
    ##1. Benchmarking with respect to a given matrix by executing the follolwing section of code, and commenting section 2.

    # Here are some examples of matrices for benchmarking. Theses where the ones used in the article.
    #P_1 matrix
    np_true_matrix = np.array([[1 / 3, 1 / 2, 1 / 6],
                               [1 / 3, 1 / 3, 1 / 3],
                               [1 / 2,  1/4 , 1 / 4 ]])
    # P_2 matrix
    # np_true_matrix = np.array([[1 / 3, 1 / 2, 1 / 6],
    #                           [1 / 2, 0, 1 / 2],
    #                           [0, 1, 0]])
    # P3 matrix
    # np_true_matrix = np.array([
    #    [1 / 3, 1 / 3, 1 / 3],
    #    [1 / 100, 99 / 100, 0],
    #    [1 / 100, 0, 99 / 100]
    # ])
    # P4 matrix
    #np_true_matrix = np.array([
    #    [1 / 1000, 999 / 1000, 0],
    #    [0, 1 / 1000, 999 / 1000],
    #    [999 / 1000, 0, 1 / 1000]
    #])


    """
    state_space = ["A", "B", "C"]
    initial_state = "A"
    n_samples = 10000
    size_largest_subsample = n_samples #most of the time taken to be equal to n_samples, but this is not mandatory
    benchmark_given_matrix(np_true_matrix=np_true_matrix,
                           state_space=state_space, initial_state=initial_state,
                           size_smallest_subsample=size_smallest_subsample,
                           size_largest_subsample=size_largest_subsample,
                           step_of_subsampling=step_of_subsampling,
                           n_samples=n_samples,
                           LIST_METHODS=LIST_METHODS)
    """
    ##2. Benchmark/Analyze the convergence of the different confidence interval methods by calling executing

    rmsd_file="AFICS/results/Ca_water/CA_water-RMSDs.csv" #adress of the csv file containing the RMSDs, generated by AFICS
    size_largest_subsample=100
    benchmark_from_AFICS(rmsd_file=rmsd_file,
                         size_smallest_subsample=size_smallest_subsample,
                         step_of_subsampling=step_of_subsampling,
                         size_largest_subsample=size_largest_subsample,
                         adress_results=adress_results,
                         LIST_METHODS=LIST_METHODS)




